### ISSUE TITLE
デザイン(画面)決める

### ISSUE THREAD

**Issue by projectormato** [projectormato/BestAlbum#1]
まあ手書きでも、なんかツール使っても

**Comment by projectormatobiz** [comment]
![Design1](https://user-images.githubusercontent.com/49631806/58867028-b185f800-86f4-11e9-9776-cda6f55ccb4a.jpg)
![Design2](https://user-images.githubusercontent.com/49631806/58867072-bf3b7d80-86f4-11e9-89f9-73abce68e214.jpg)

**Comment by projectormato** [comment]
Figmaでも作成しました。
https://www.figma.com/file/Jv52G8fRoRMWR86P457QM00L/MyFirstFigma?node-id=0%3A1
